# Generated by Django 4.1.4 on 2022-12-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, verbose_name='Nombre del evento')),
                ('inicio', models.DateField(verbose_name='Fecha de apertura')),
                ('fin', models.DateField(verbose_name='Fecha de cierre')),
                ('lugar', models.CharField(max_length=250, verbose_name='Lugar')),
                ('detalle', models.TextField(null=True)),
                ('disponibles', models.IntegerField(default=300)),
                ('vendidos', models.IntegerField(default=0)),
                ('canjeados', models.IntegerField(default=0)),
                ('status_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
    ]
